package explanation;

/**
 * ╔══════════════════════════════════════════════════════════════════╗
 * ║  FILE   : EnumDemo.java                                          ║
 * ║  MODULE : 00-java-foundation / 03-advanced-oop                   ║
 * ║  GRADLE : ./gradlew :00-java-foundation:run --args="EnumDemo"    ║
 * ╠══════════════════════════════════════════════════════════════════╣
 * ║  PURPOSE        : Demonstrates that Enums are full classes       ║
 * ║  WHY IT EXISTS  : Type safety over integer/string constants      ║
 * ║  PYTHON COMPARE : from enum import Enum. But Java enums are full ║
 * ║                   objects with custom logic and state.           ║
 * ║  USE CASES      : Status flows, predefined configurations, cards ║
 * ╠══════════════════════════════════════════════════════════════════╣
 * ║  ASCII DIAGRAM                                                    ║
 * ║    OrderStatus [Enum]                                             ║
 * ║    ├── NEW (code=100)                                             ║
 * ║    ├── PROCESSING (code=200)                                      ║
 * ║    └── SHIPPED (code=300)                                         ║
 * ║         └─ int code                                               ║
 * ║         └─ String description                                     ║
 * ║         └─ boolean isTerminal()                                   ║
 * ╠══════════════════════════════════════════════════════════════════╣
 * ║  HOW TO RUN     : ./gradlew :00-java-foundation:run --args="EnumDemo" ║
 * ║  EXPECTED OUTPUT: Ordinals, Values, and custom Enum behavior     ║
 * ║  RELATED FILES  : 02-enums.md                                    ║
 * ╚══════════════════════════════════════════════════════════════════╝
 */
public class EnumDemo {

    // A full-featured Java Enum
    public enum OrderStatus {
        // 1. The instances MUST be declared first!
        NEW(100, "Order just placed"),
        PROCESSING(200, "Warehouse is actively packing your order"),
        SHIPPED(300, "Order is on the truck"),
        DELIVERED(400, "Package in hand"),
        CANCELLED(500, "Order was aborted");

        // 2. These are the instance fields each enum value holds
        private final int dbCode;
        private final String description;

        // 3. The constructor is ALWAYS implicitly private.
        // It is called exactly once per constant when the class is loaded.
        OrderStatus(int dbCode, String description) {
            this.dbCode = dbCode;
            this.description = description;
        }

        // 4. Enums can have standard methods!
        public int getDbCode() {
            return dbCode;
        }

        public String getDescription() {
            return description;
        }

        // 5. Enums can have complex business logic!
        public boolean isTerminalState() {
            return this == DELIVERED || this == CANCELLED;
        }
    }

    public static void main(String[] args) {
        System.out.println("--- 1. Using Enum Constants ---");
        OrderStatus currentStatus = OrderStatus.PROCESSING;
        System.out.println("Current Status: " + currentStatus);                 // Prints name: PROCESSING
        System.out.println("Description:    " + currentStatus.getDescription());  // Prints custom field

        System.out.println("\n--- 2. Enum Built-in Methods ---");
        System.out.println("Exact string name: " + currentStatus.name());       // "PROCESSING"
        System.out.println("0-based index:     " + currentStatus.ordinal());    // 1 (Do not use this for DB storage!)

        System.out.println("\n--- 3. Iterating over Enums ---");
        // .values() is automatically generated by the Java compiler
        for (OrderStatus status : OrderStatus.values()) {
            System.out.printf("[%d] %s => Terminal? %b%n", 
                                status.getDbCode(), 
                                status.name(), 
                                status.isTerminalState());
        }

        System.out.println("\n--- 4. String to Enum Conversion ---");
        try {
            // Must match the exact spelling and case
            OrderStatus parsed = OrderStatus.valueOf("SHIPPED");
            System.out.println("Successfully parsed 'SHIPPED' to: " + parsed);
            
            OrderStatus badParse = OrderStatus.valueOf("shipped"); // Throws exception!
        } catch (IllegalArgumentException e) {
            System.out.println("Failed to parse lowercase 'shipped'!");
        }

        System.out.println("\n--- 5. Switch-Case with Enums ---");
        // Java switch statements are perfectly optimized for Enums
        switch (currentStatus) {
            case NEW:
                // Note: you write NEW, not OrderStatus.NEW inside the case!
                System.out.println("Payment not yet cleared.");
                break;
            case PROCESSING:
            case SHIPPED:
                System.out.println("Items are moving!");
                break;
            default:
                System.out.println("Terminal state reached.");
        }
    }
}
